# Generated by Django 5.0.6 on 2026-07-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Especificaciones'),
        ),
    ]
