# Generated by Django 5.2.15 on 2026-07-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, verbose_name='Segundo Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='updated_at',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='especificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Especificaciones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Llegada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Referencial'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin Marca', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría'),
        ),
    ]
