# Generated by Django 5.2.15 on 2026-08-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_caja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo por caja'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_caja',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta por caja'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo por unidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta por unidad'),
        ),
    ]
