# Generated by Django 5.2.15 on 2026-07-21 03:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco'), ('ahorro', 'Ahorro'), ('otro', 'Otro')], default='caja', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ingres', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
            ],
            options={
                'verbose_name': 'Categoría financiera',
                'verbose_name_plural': 'Categorías financieras',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingresos'), ('egreso', 'Egreso')], max_length=20)),
                ('origen', models.CharField(choices=[('venta_producto', 'Venta de producto'), ('servicio_mantenimiento', 'Servicio de mantenimiento'), ('compra', 'Cpompra'), ('gasto_manual', 'Gasto manual'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finance.categoriafinanciera')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finance.cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento financiero',
                'verbose_name_plural': 'Movimientos financieros',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
